<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

        <!-- Global stylesheets -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">



        <?=
                $this->headLink()->prependStylesheet($this->basePath('assets/css/icons/icomoon/styles.css'))
                ->prependStylesheet($this->basePath('assets/css/bootstrap.css'))
                ->prependStylesheet($this->basePath('assets/css/core.css'))
                ->prependStylesheet($this->basePath('assets/css/components.css'))
                ->prependStylesheet($this->basePath('assets/css/colors.css'));
        ?>
        <!-- /global stylesheets -->

        <!-- Core JS files -->



        <?=
                $this->headScript()
                ->prependFile($this->basePath('assets/js/plugins/loaders/pace.min.js'))
                ->prependFile($this->basePath('assets/js/core/libraries/bootstrap.min.js'))
                ->prependFile($this->basePath('assets/js/plugins/loaders/blockui.min.js'))
                ->prependFile($this->basePath('assets/js/plugins/forms/styling/uniform.min.js'))
                ->prependFile($this->basePath('assets/js/core/app.js'))
                ->prependFile($this->basePath('assets/js/pages/login.js'))
                ->prependFile($this->basePath('assets/js/core/libraries/jquery.min.js'))
        ?>

        <!-- /core JS files -->

        <!-- Theme JS files -->
        
        <!-- /theme JS files -->

    </head>

    <body class="login-container">

        <!-- Main navbar -->
        <div class="navbar navbar-inverse bg-indigo">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><img src="http://localhost:8081/shop/public/assets/images/logo_light.png" alt=""></a>

                <ul class="nav navbar-nav pull-right visible-xs-block">
                    <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
                </ul>
            </div>

            <div class="navbar-collapse collapse" id="navbar-mobile">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <i class="icon-display4"></i> <span class="visible-xs-inline-block position-right"> Go to website</span>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="icon-user-tie"></i> <span class="visible-xs-inline-block position-right"> Contact admin</span>
                        </a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-cog3"></i>
                            <span class="visible-xs-inline-block position-right"> Options</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /main navbar -->


        <!-- Page container -->
        <div class="page-container">

            <!-- Page content -->
            <div class="page-content">

                <!-- Main content -->
                <div class="content-wrapper">

                    <!-- Content area -->
                    <div class="content">

                        <!-- Advanced login -->
                        <form method="post">
                            <div class="panel panel-body login-form">
                                <div class="text-center">
                                    <div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
                                    <h5 class="content-group">Đăng nhập tài khoản của bạn <small class="display-block">Thông tin tài khoản</small></h5>
                                </div>

                                <div class="form-group has-feedback has-feedback-left">
                                    <input type="text" class="form-control" placeholder="Username" name="username">
                                    <div class="form-control-feedback">
                                        <i class="icon-user text-muted"></i>
                                    </div>
                                </div>

                                <div class="form-group has-feedback has-feedback-left">
                                    <input type="password" class="form-control" placeholder="Password" name="password">
                                    <div class="form-control-feedback">
                                        <i class="icon-lock2 text-muted"></i>
                                    </div>
                                </div>
                                <div style="color: red;text-align: center;margin-bottom: 10px"><?= $this->content ?></div>

                                <div class="form-group login-options">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <label class="checkbox-inline">
                                                <input type="checkbox" class="styled" checked="checked">
                                                Ghi nhớ
                                            </label>
                                        </div>

                                        <div class="col-sm-6 text-right">
                                            <a href="login_password_recover.html">Bạn quên mật khẩu?</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn bg-pink-400 btn-block">Đăng nhập <i class="icon-arrow-right14 position-right"></i></button>
                                </div>

                                <div class="content-divider text-muted form-group"><span>Đăng nhập với</span></div>
                                <ul class="list-inline form-group list-inline-condensed text-center">
                                    <li><a href="#" class="btn border-indigo text-indigo btn-flat btn-icon btn-rounded"><i class="icon-facebook"></i></a></li>
                                    <li><a href="#" class="btn border-pink-300 text-pink-300 btn-flat btn-icon btn-rounded"><i class="icon-dribbble3"></i></a></li>
                                    <li><a href="#" class="btn border-slate-600 text-slate-600 btn-flat btn-icon btn-rounded"><i class="icon-github"></i></a></li>
                                    <li><a href="#" class="btn border-info text-info btn-flat btn-icon btn-rounded"><i class="icon-twitter"></i></a></li>
                                </ul>

                                <div class="content-divider text-muted form-group"><span>Bạn không có tài khoản?</span></div>
                                <a href="login_registration.html" class="btn btn-default btn-block content-group">Đăng ký</a>
                                <span class="help-block text-center no-margin">By continuing, you're confirming that you've read our <a href="#">Terms &amp; Conditions</a> and <a href="#">Cookie Policy</a></span>
                            </div>
                        </form>
                        <!-- /advanced login -->


                        <!-- Footer -->
                        <div class="footer text-muted text-center">
                            &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
                        </div>
                        <!-- /footer -->

                    </div>
                    <!-- /content area -->

                </div>
                <!-- /main content -->

            </div>
            <!-- /page content -->

        </div>
        <!-- /page container -->

    </body>
</html>
