<!-- page content -->
<div class="right_col" role="main">

        <div class="page-title">
            <div class="title_left">
                <h3>Thêm mới sản phẩm</h3>
            </div>
        </div>
    <div class="clearfix"></div>
    <form>
        <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <div class="product_face">
                            <a class="btn">
                                <img src="https://www.google.com.vn/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="width: 250px;height: auto" title="Nhấp để thay đổi ảnh nền">
                            </a>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">
                        <br />
                        <div class="form-horizontal form-label-left">

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tên sản phẩm</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" placeholder="Tên sản phẩm" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Xuất xứ</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <div class="input-group dropdown ">

                                        <input type="text" class="form-control list_item" placeholder="Xuất xứ" required>
                                        <div class="input-group-addon">
                                            <a class="dropdown-toggle select-menu-size" href="#" data-toggle="dropdown">
                                                <span class="caret"></span></a>
                                            <!--                                            aria-expanded = true/false su kien-->
                                            <ul class="dropdown-menu dropdown-menu-left menu-size" style="width: 100%">
                                                <li><a >HTML</a></li>
                                                <li><a >CSS</a></li>
                                                <li><a >JavaScript</a></li>
                                                <li class="new-size"><a></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                </div>

                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Kích cỡ</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <div class="input-group dropdown ">

                                        <input type="text" class="form-control list_item" placeholder="Kích cỡ">
                                        <div class="input-group-addon">
                                            <a class="dropdown-toggle select-menu-size" href="#" data-toggle="dropdown">
                                                <span class="caret"></span></a>
                                            <!--                                            aria-expanded = true/false su kien-->
                                            <ul class="dropdown-menu dropdown-menu-left menu-size" style="width: 100%">
                                                <li><a >HTML</a></li>
                                                <li><a >CSS</a></li>
                                                <li><a >JavaScript</a></li>
                                                <li class="new-size"><a></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                </div>

                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Giới tính</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <div class="input-group dropdown ">

                                        <input type="text" class="form-control list_item" placeholder="Giới tính">
                                        <div class="input-group-addon">
                                            <a class="dropdown-toggle select-menu-size" href="#" data-toggle="dropdown">
                                                <span class="caret"></span></a>
                                            <!--                                            aria-expanded = true/false su kien-->
                                            <ul class="dropdown-menu dropdown-menu-left menu-size" style="width: 100%">
                                                <li><a >HTML</a></li>
                                                <li><a >CSS</a></li>
                                                <li><a >JavaScript</a></li>
                                                <li class="new-size"><a></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                </div>

                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Nhóm sản phẩm</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <select class="select2_group form-control">
                                        <optgroup label="Alaskan/Hawaiian Time Zone">
                                            <option value="AK">Alaska</option>
                                            <option value="HI">Hawaii</option>
                                        </optgroup>
                                        <optgroup label="Pacific Time Zone">
                                            <option value="CA">California</option>
                                            <option value="NV">Nevada</option>
                                            <option value="OR">Oregon</option>
                                            <option value="WA">Washington</option>
                                        </optgroup>
                                        <optgroup label="Mountain Time Zone">
                                            <option value="AZ">Arizona</option>
                                            <option value="CO">Colorado</option>
                                            <option value="ID">Idaho</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="UT">Utah</option>
                                            <option value="WY">Wyoming</option>
                                        </optgroup>
                                        <optgroup label="Central Time Zone">
                                            <option value="AL">Alabama</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TX">Texas</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="WI">Wisconsin</option>
                                        </optgroup>
                                        <optgroup label="Eastern Time Zone">
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="IN">Indiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="OH">Ohio</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WV">West Virginia</option>
                                        </optgroup>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Giá</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="number" class="form-control" min="0" required>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tag seo</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" />
                                    <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                                </div>
                            </div>




                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Nhập thông tin về sản phẩm</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="alerts"></div>
                    <div class="btn-toolbar editor" data-role="editor-toolbar" data-target="#editor-one">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="fa fa-font"></i><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                            </ul>
                        </div>

                        <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a data-edit="fontSize 5">
                                        <p style="font-size:17px">Huge</p>
                                    </a>
                                </li>
                                <li>
                                    <a data-edit="fontSize 3">
                                        <p style="font-size:14px">Normal</p>
                                    </a>
                                </li>
                                <li>
                                    <a data-edit="fontSize 1">
                                        <p style="font-size:11px">Small</p>
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                            <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                            <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                            <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
                        </div>

                        <div class="btn-group">
                            <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
                            <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
                            <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-dedent"></i></a>
                            <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
                        </div>

                        <div class="btn-group">
                            <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
                            <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
                            <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
                            <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
                        </div>

                        <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
                            <div class="dropdown-menu input-append">
                                <input class="span2" placeholder="URL" type="text" data-edit="createLink" />
                                <button class="btn" type="button">Add</button>
                            </div>
                            <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
                        </div>

                        <div class="btn-group">
                            <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="fa fa-picture-o"></i></a>
                            <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
                        </div>

                        <div class="btn-group">
                            <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
                            <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
                        </div>
                    </div>

                    <div id="editor-one" class="editor-wrapper"></div>

                    <textarea name="descr" id="descr" style="display:none;" required></textarea>

                    <br />

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-8">
                            <button type="reset" class="btn btn-primary">Nhập lại</button>
                            <button type="submit" class="btn btn-success">Đăng ký</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>
<!-- /page content -->
<!-- jQuery -->
<script src="<?= $this->basePath("vendors/jquery/dist/jquery.min.js") ?>"></script>
<!-- Bootstrap -->
<script src="<?= $this->basePath("vendors/bootstrap/dist/js/bootstrap.min.js") ?>"></script>
<!-- FastClick -->
<script src="<?= $this->basePath("vendors/fastclick/lib/fastclick.js") ?>"></script>
<!-- NProgress -->
<script src="<?= $this->basePath("vendors/nprogress/nprogress.js") ?>"></script>
<!-- bootstrap-progressbar -->
<script src="<?= $this->basePath("vendors/bootstrap-progressbar/bootstrap-progressbar.min.js") ?>"></script>
<!-- iCheck -->
<script src="<?= $this->basePath("vendors/iCheck/icheck.min.js") ?>"></script>
<!-- bootstrap-daterangepicker -->
<script src="<?= $this->basePath("vendors/moment/min/moment.min.js") ?>"></script>
<script src="<?= $this->basePath("vendors/bootstrap-daterangepicker/daterangepicker.js") ?>"></script>
<!-- bootstrap-wysiwyg -->
<script src="<?= $this->basePath("vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js") ?>"></script>
<script src="<?= $this->basePath("vendors/jquery.hotkeys/jquery.hotkeys.js") ?>"></script>
<script src="<?= $this->basePath("vendors/google-code-prettify/src/prettify.js") ?>"></script>
<!-- jQuery Tags Input -->
<script src="<?= $this->basePath("vendors/jquery.tagsinput/src/jquery.tagsinput.js") ?>"></script>
<!-- Switchery -->
<script src="<?= $this->basePath("vendors/switchery/dist/switchery.min.js") ?>"></script>
<!-- Select2 -->
<script src="<?= $this->basePath("vendors/select2/dist/js/select2.full.min.js") ?>"></script>
<!-- Parsley -->
<script src="<?= $this->basePath("vendors/parsleyjs/dist/parsley.min.js") ?>"></script>
<!-- Autosize -->
<script src="<?= $this->basePath("vendors/autosize/dist/autosize.min.js") ?>"></script>
<!-- jQuery autocomplete -->
<script src="<?= $this->basePath("vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js") ?>"></script>
<!-- starrr -->
<script src="<?= $this->basePath("vendors/starrr/dist/starrr.js") ?>"></script>
<!-- Custom Theme Scripts -->
<script src="<?= $this->basePath("build/js/custom.min.js") ?>"></script>
<script src="<?= $this->basePath("build/js/product_table_add.js")?>"></script>