<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h6><i class="icon-home2 position-left"></i> <span class="text-semibold"><a href="#">Trang chủ</a> / Người dùng</span></h6>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Danh sách người dùng</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>



        <table class="table datatable-selection-single">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tài khoản</th>
                    <th>Họ tên</th>
                    <th>Địa chỉ</th>
                    <th>Quyền truy cập</th>
                    <th><a href="<?= $this->url('admin/usertable',array("action" => "add")) ?>"><i class="glyphicon glyphicon-plus" style="font-size: 30px;color: #33FF66"></i></a></th>
                </tr>
            </thead>

            <?php
            foreach ($this->table as $row) {
                echo '<tbody class="parent"><td><a href="'.$this->url('admin/usertable',array('action'=>'edit')).'?id='.$row['id_nguoidung'].'">#' . $row['id_nguoidung'] . '</a></td>';
                echo '<td>' . $row['taikhoan'] . '</td>';
                echo '<td>' . $row['ho'] . ' ' . $row['tendem'] . ' ' . $row['ten'] . '</td>';
                echo '<td>' . $row['diachi'] . '</td>';
                switch ($row['quyentruycap']) {
                    case 1:
                        echo '<td>Người dùng</td>';
                        break;
                    case 2:
                        echo '<td>Quản lý</td>';
                        break;
                    case 3:
                        echo '<td>Admin</td>';
                        break;
                    default :
                        echo '<td>null</td>';
                }
                echo '<td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                    <a class="xoa" data-toggle="confirmation" data-title="' . $row['id_nguoidung'] . '">Xóa<i class="glyphicon glyphicon-remove"></i></a>
                                    </li>
                                    
                                    
                                </ul>
                            </li>
                        </ul>
                    </td></tbody>';
            }
            ?>


        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.xoa').click(function () {
           
            var id =  $(this).attr('data-title');
            
            bootbox.confirm("<h3>Bạn chắc chắn muốn xóa chứ?</h3>", function (result) {
               
                if (result === true)
                {
                    $.ajax({
                        type: "POST",
                        url: "<?= $this->url('admin/usertable', array('action' => 'delete')) ?>",
                        data: {
                            id: id
                        },
                        success: function (data) {
                            json = JSON.parse(data);
                            if(json.id === true)
                            {
                                window.location.reload();
                            }
                        },
                        dataType: 'json'
                    });
                }
            });
        });
    });
</script>